### ISSUE TITLE
slink calc function needs to support clusters

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/LincServe#17]

**Comment by borgmaan** [comment]
I was toying around with this idea last week. Ideally, the underlying code would remain the same whether we were parallelizing across multiple cores on a single machine or across multiple cores distributed across a network of machines.

One way to do this would be to use the [`foreach`](https://cran.r-project.org/web/packages/foreach/index.html) package with multiple parallel back ends -- the [`doMC`](https://cran.r-project.org/web/packages/doMC/index.html) package for single machine parallelism and the [`doSNOW`](https://cran.r-project.org/web/packages/doSNOW/index.html) package if we are working with a network of machines. 

Setting the parallel back end would look something like this:

```
Slinky$methods(calc = function(method = NULL, cores = NULL, cluster = NULL) {
  if (is.null(cores) & is.null(cluster)) {
    message("Running calculations serially. Specify cores to run in parallel...")
  } else if (!is.null(cluster)) {
    if (!("cluster" %in% class(cluster))) stop('Cluster must be created by snow library...')
    registerDoSNOW(cluster)
  } else if (!is.null(cores)) {
    registerDoMC(cores)
  }
...
})
```

With the back end successfully registered you can decorate your `foreach` loops with `%dopar%` and they will be parallelized with the appropriate back end. 

For the `snow` backed loops I still need to work out the full set of objects I need to copy over and libraries I need to load on each node using some combo of `clusterExport`/`clusterApply`/`cluster....`.

I was tempted to just try `clusterExport(ls())`, but some smart people [say that is a bad idea](http://stackoverflow.com/a/12232695).

**Comment by erikor** [comment]
Not so much A Bad Idea™ as aesthetically unpleasing design.  Fine to do it for now I would say.  Agree that we should seamlessly support both scenarios.

**Comment by borgmaan** [comment]
Finally solved the issue with help from this post:

http://stackoverflow.com/questions/12023403/using-parlapply-and-clusterexport-inside-a-function
